apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp-replicase
spec:
  selector:
    matchLabels:
      tier: frontend
      end: dev
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: myapp-replicase
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9